### ISSUE TITLE
License on Nuget is missing

### ISSUE THREAD

**Issue by reiz** [dlemstra/line-bot-sdk-dotnet#1]
I'm not a .NET guy but many packages which are published on Nuget are exposing a license. Some how this package doesn't expose it's license via the Nuget API. See here: https://www.nuget.org/packages/LineBotSDK. It would be nice if the license would show up on the Nuget page as well. That would it make much easier to fetch the license automatically, for tools like [VersionEye](https://www.versioneye.com).

**Comment by dlemstra** [comment]
You are linking to the wrong package or reporting the issue in the wrong project. This is my NuGet package: https://www.nuget.org/packages/Line.Bot.SDK

**Comment by reiz** [comment]
Many Thanks for your quick response.
