### ISSUE TITLE
get exception

### ISSUE THREAD

**Issue by amshuo** [dlemstra/line-bot-sdk-dotnet#12]
I'm get a Line.LineBotException: Not found  when trying use push method.

What that's mean?  and why? anything wrong?

**Comment by dlemstra** [comment]
Can you please include a small code sample that reproduces this error?

**Comment by dlemstra** [comment]
@amshuo Did you figure out what caused this?

**Comment by amshuo** [comment]
It's line id not found. after using correct id , problem is solved
