### ISSUE TITLE
UserProfile encoding

### ISSUE THREAD

**Issue by amshuo** [dlemstra/line-bot-sdk-dotnet#4]
hi~ your sdk is easily to use, thx..

but now IUserProfile.Displayname property retrun  '???' when i call GetProfile()

i guess...Displayname encoding is big5 ?

**Comment by dlemstra** [comment]
How did you solve this issue?

**Comment by amshuo** [comment]
sorry my bad~
I forgot that output file log is encode by utf-8
So...will see Displayname ->  '???'

**Comment by dlemstra** [comment]
Thanks for coming back so other people who also run into this might might be able to resolve their issue faster. 👍
