### ISSUE TITLE
Change the return type of GetEvents to include the "destination".

### ISSUE THREAD

**Issue by dlemstra** [dlemstra/line-bot-sdk-dotnet#46]
https://developers.line.me/en/reference/messaging-api/#request-body

**Comment by charliedua** [comment]
I looked at what this issue requires but changing the return type will make a big impact as it has 27 references where it is being used. So changing the return type will cause a lot of hassle and effort.
![image](https://user-images.githubusercontent.com/33629087/48202978-71f36980-e3ba-11e8-8d23-11eb6ecf7198.png)
However all the references are in the tests project and is not used by any other part in the class library.
![image](https://user-images.githubusercontent.com/33629087/48203108-b7b03200-e3ba-11e8-854d-b15ae79f94be.png) 
Moreover if the return type has to be changed a Tuple can be used to return two types at once.

**Comment by charliedua** [comment]
> I'll be happy to work on this task.

What I am planning to change: 
1. adding a new property
    - File: ILineEvent.cs
    - name: Destination
    - DataType: string
    - Accessibility: get
2. Files Impacted By this change: 
    - LineEvent.cs
3. Changes in LineEvent.cs
    - new field for Destination, name _destination, type String Default value null, encapsulation level private.
    - new override property for Destination
        - Attribute: [JsonProperty("destination")]

Could you confirm this is the way to go. Cheers.

**Comment by dlemstra** [comment]
I would rather see a new interface `ILineEvents: IEnumerable<ILineEvent>` instead that has this `Destination` property. I don't think we need this on the `ILineEvent` interface. We then also need a internal class called `LineEvents` that implements this. The `"events"` property on that class can be hidden for the outside world.

**Comment by charliedua** [comment]
I'll start working on it in some time. ( ~ 15 hours). I'll confirm the changes made in a PR.

**Comment by dlemstra** [comment]
Thanks @charliedua!

**Comment by dlemstra** [comment]
We could use `ILineEvents` for the outside world and use `LineEventCollection` internally. And you should indeed add the property to that class.
